// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viridisca.Modules.Curriculum.Infrastructure.Database;

#nullable disable

namespace Viridisca.Modules.Curriculum.Infrastructure.Migrations
{
    [DbContext(typeof(CurriculumDbContext))]
    [Migration("20260824210046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("curriculum")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.AcademicPeriod", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("integer")
                        .HasColumnName("academic_year");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Uid")
                        .HasName("pk_academic_periods");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_academic_periods_code");

                    b.ToTable("academic_periods", "curriculum");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.Assignment", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid>("CourseInstanceUid")
                        .HasColumnType("uuid")
                        .HasColumnName("course_instance_uid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("max_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Uid")
                        .HasName("pk_assignments");

                    b.HasIndex("CourseInstanceUid")
                        .HasDatabaseName("ix_assignments_course_instance_uid");

                    b.ToTable("assignments", "curriculum");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.CourseInstance", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid>("AcademicPeriodUid")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_period_uid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("GroupUid")
                        .HasColumnType("uuid")
                        .HasColumnName("group_uid");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<int>("MaxEnrollments")
                        .HasColumnType("integer")
                        .HasColumnName("max_enrollments");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectUid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_uid");

                    b.Property<Guid?>("TeacherUid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_uid");

                    b.HasKey("Uid")
                        .HasName("pk_course_instances");

                    b.HasIndex("AcademicPeriodUid")
                        .HasDatabaseName("ix_course_instances_academic_period_uid");

                    b.HasIndex("GroupUid")
                        .HasDatabaseName("ix_course_instances_group_uid");

                    b.HasIndex("SubjectUid")
                        .HasDatabaseName("ix_course_instances_subject_uid");

                    b.HasIndex("TeacherUid")
                        .HasDatabaseName("ix_course_instances_teacher_uid");

                    b.ToTable("course_instances", "curriculum");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.Submission", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid>("AssignmentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_uid");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_path");

                    b.Property<DateTime?>("GradedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graded_at_utc");

                    b.Property<Guid?>("GradedByUid")
                        .HasColumnType("uuid")
                        .HasColumnName("graded_by_uid");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("student_uid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submission_date");

                    b.HasKey("Uid")
                        .HasName("pk_submissions");

                    b.HasIndex("GradedByUid")
                        .HasDatabaseName("ix_submissions_graded_by_uid");

                    b.HasIndex("StudentUid")
                        .HasDatabaseName("ix_submissions_student_uid");

                    b.HasIndex("AssignmentUid", "StudentUid")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_assignment_uid_student_uid");

                    b.ToTable("submissions", "curriculum");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.Assignment", b =>
                {
                    b.HasOne("Viridisca.Modules.Curriculum.Domain.Models.CourseInstance", null)
                        .WithMany()
                        .HasForeignKey("CourseInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignments_course_instances_course_instance_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.CourseInstance", b =>
                {
                    b.HasOne("Viridisca.Modules.Curriculum.Domain.Models.AcademicPeriod", null)
                        .WithMany()
                        .HasForeignKey("AcademicPeriodUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_instances_academic_periods_academic_period_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Curriculum.Domain.Models.Submission", b =>
                {
                    b.HasOne("Viridisca.Modules.Curriculum.Domain.Models.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_assignments_assignment_uid");
                });
#pragma warning restore 612, 618
        }
    }
}
