// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viridisca.Modules.Academic.Infrastructure.Database;

#nullable disable

namespace Viridisca.Modules.Academic.Infrastructure.Migrations
{
    [DbContext(typeof(AcademicDbContext))]
    [Migration("20260824195926_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("academic")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CuratorUid")
                        .HasColumnType("uuid")
                        .HasColumnName("curator_uid");

                    b.Property<Guid>("DepartmentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("department_uid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer")
                        .HasColumnName("max_students");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Uid")
                        .HasName("pk_groups");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_code");

                    b.HasIndex("CuratorUid")
                        .HasDatabaseName("ix_groups_curator_uid");

                    b.HasIndex("DepartmentUid")
                        .HasDatabaseName("ix_groups_department_uid");

                    b.ToTable("groups", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("GraduationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("graduation_date");

                    b.Property<Guid?>("GroupUid")
                        .HasColumnType("uuid")
                        .HasColumnName("group_uid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("MedicalInformation")
                        .HasColumnType("text")
                        .HasColumnName("medical_information");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("Uid")
                        .HasName("pk_students");

                    b.HasIndex("GroupUid")
                        .HasDatabaseName("ix_students_group_uid");

                    b.HasIndex("StudentCode")
                        .IsUnique()
                        .HasDatabaseName("ix_students_student_code");

                    b.HasIndex("UserUid")
                        .IsUnique()
                        .HasDatabaseName("ix_students_user_uid");

                    b.ToTable("students", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.StudentParent", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("HasLegalGuardianship")
                        .HasColumnType("boolean")
                        .HasColumnName("has_legal_guardianship");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_contact");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid>("ParentUserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_uid");

                    b.Property<int>("Relation")
                        .HasColumnType("integer")
                        .HasColumnName("relation");

                    b.Property<Guid>("StudentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("student_uid");

                    b.HasKey("Uid")
                        .HasName("pk_student_parents");

                    b.HasIndex("StudentUid", "ParentUserUid")
                        .IsUnique()
                        .HasDatabaseName("ix_student_parents_student_uid_parent_user_uid");

                    b.ToTable("student_parents", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Subject", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<Guid?>("DepartmentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("department_uid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<int?>("MinimumRequiredGrade")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_required_grade");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Syllabus")
                        .HasColumnType("text")
                        .HasColumnName("syllabus");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Uid")
                        .HasName("pk_subjects");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subjects_code");

                    b.HasIndex("DepartmentUid")
                        .HasDatabaseName("ix_subjects_department_uid");

                    b.ToTable("subjects", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Teacher", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DepartmentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("department_uid");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employee_code");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hire_date");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text")
                        .HasColumnName("qualifications");

                    b.Property<string>("Specialization")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("specialization");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Uid")
                        .HasName("pk_teachers");

                    b.HasIndex("DepartmentUid")
                        .HasDatabaseName("ix_teachers_department_uid");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_employee_code");

                    b.HasIndex("UserUid")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_user_uid");

                    b.ToTable("teachers", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.TeacherGroup", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<Guid>("GroupUid")
                        .HasColumnType("uuid")
                        .HasColumnName("group_uid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_curator");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid>("SubjectUid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_uid");

                    b.Property<Guid>("TeacherUid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_uid");

                    b.HasKey("Uid")
                        .HasName("pk_teacher_groups");

                    b.HasIndex("GroupUid")
                        .HasDatabaseName("ix_teacher_groups_group_uid");

                    b.HasIndex("SubjectUid")
                        .HasDatabaseName("ix_teacher_groups_subject_uid");

                    b.HasIndex("TeacherUid", "GroupUid", "SubjectUid")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_groups_teacher_uid_group_uid_subject_uid");

                    b.ToTable("teacher_groups", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.TeacherSubject", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsMainTeacher")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main_teacher");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid>("SubjectUid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_uid");

                    b.Property<Guid>("TeacherUid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_uid");

                    b.HasKey("Uid")
                        .HasName("pk_teacher_subjects");

                    b.HasIndex("SubjectUid")
                        .HasDatabaseName("ix_teacher_subjects_subject_uid");

                    b.HasIndex("TeacherUid", "SubjectUid")
                        .IsUnique()
                        .HasDatabaseName("ix_teacher_subjects_teacher_uid_subject_uid");

                    b.ToTable("teacher_subjects", "academic");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Student", b =>
                {
                    b.HasOne("Viridisca.Modules.Academic.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupUid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_students_groups_group_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.StudentParent", b =>
                {
                    b.HasOne("Viridisca.Modules.Academic.Domain.Models.Student", null)
                        .WithMany("Parents")
                        .HasForeignKey("StudentUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_parents_students_student_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.TeacherGroup", b =>
                {
                    b.HasOne("Viridisca.Modules.Academic.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_groups_groups_group_uid");

                    b.HasOne("Viridisca.Modules.Academic.Domain.Models.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_groups_subjects_subject_uid");

                    b.HasOne("Viridisca.Modules.Academic.Domain.Models.Teacher", null)
                        .WithMany("Groups")
                        .HasForeignKey("TeacherUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_groups_teachers_teacher_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.TeacherSubject", b =>
                {
                    b.HasOne("Viridisca.Modules.Academic.Domain.Models.Subject", null)
                        .WithMany("Teachers")
                        .HasForeignKey("SubjectUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_subjects_subjects_subject_uid");

                    b.HasOne("Viridisca.Modules.Academic.Domain.Models.Teacher", null)
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_subjects_teachers_teacher_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Student", b =>
                {
                    b.Navigation("Parents");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Subject", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Viridisca.Modules.Academic.Domain.Models.Teacher", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
