// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Viridisca.Modules.Grading.Infrastructure.EF;

#nullable disable

namespace Viridisca.Modules.Grading.Infrastructure.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    [Migration("20260824203441_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("grading")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.Grade", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LessonUid")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_uid");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("StudentUid")
                        .HasColumnType("uuid")
                        .HasColumnName("student_uid");

                    b.Property<Guid>("SubjectUid")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_uid");

                    b.Property<Guid>("TeacherUid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_uid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("value");

                    b.HasKey("Uid")
                        .HasName("pk_grades");

                    b.ToTable("grades", "grading");
                });

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.GradeComment", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<Guid>("AuthorUid")
                        .HasColumnType("uuid")
                        .HasColumnName("author_uid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid>("GradeUid")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_uid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Uid")
                        .HasName("pk_grade_comments");

                    b.HasIndex("GradeUid")
                        .HasDatabaseName("ix_grade_comments_grade_uid");

                    b.ToTable("grade_comments", "grading");
                });

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.GradeRevision", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("GradeUid")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_uid");

                    b.Property<string>("NewDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("new_description");

                    b.Property<decimal>("NewValue")
                        .HasColumnType("numeric")
                        .HasColumnName("new_value");

                    b.Property<string>("PreviousDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("previous_description");

                    b.Property<decimal>("PreviousValue")
                        .HasColumnType("numeric")
                        .HasColumnName("previous_value");

                    b.Property<string>("RevisionReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revision_reason");

                    b.Property<Guid>("TeacherUid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_uid");

                    b.HasKey("Uid")
                        .HasName("pk_grade_revisions");

                    b.HasIndex("GradeUid")
                        .HasDatabaseName("ix_grade_revisions_grade_uid");

                    b.ToTable("grade_revisions", "grading");
                });

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.GradeComment", b =>
                {
                    b.HasOne("Viridisca.Modules.Grading.Domain.Models.Grade", null)
                        .WithMany("Comments")
                        .HasForeignKey("GradeUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_comments_grades_grade_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.GradeRevision", b =>
                {
                    b.HasOne("Viridisca.Modules.Grading.Domain.Models.Grade", null)
                        .WithMany("Revisions")
                        .HasForeignKey("GradeUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grade_revisions_grades_grade_uid");
                });

            modelBuilder.Entity("Viridisca.Modules.Grading.Domain.Models.Grade", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
